<?php $this->appendCss("/css/atp-cms/cms.less")?>

<div class="cms-page" id="cms-page-<?=$page->url?>">
	<h1><?=$page->title?></h1>
	<p class="cms-post-date"><?=date($this->siteParam('cms-date-format'), strtotime($page->postDate))?></p>
	<div class="cms-page-content"><?=$page->contentHtml?></div>
</div>

<style type="text/css">
	<?=$page->extraCss?>
</style>

<script type="text/javascript">
	<?=$page->script?>
</script>
