<?php $this->pageType("cms-page")?>
<?php $this->breadcrumbs($page->title, $this->basePath($page->url)) ?>
<?php $this->headTitle($page->title)?>
<?php $this->appendCss("/atp-cms/css/cms.less")?>

<?php if($page->category->name && $page->category->isViewable) {
	$this->breadcrumbs($page->category->name, $this->basePath("cms/category/" . $page->category->url));
	$this->headTitle($page->category->name);
} ?>

<div class="cms-page" id="cms-page-<?=$page->url?>">
	<h1><?=$page->title?></h1>
	<p class="cms-post-date"><?=date($this->siteParam('cms-date-format'), strtotime($page->postDate))?></p>
	<div class="cms-page-content"><?=$page->contentHtml?></div>
</div>

<style type="text/css">
	<?=$page->extraCss?>
</style>

<script type="text/javascript">
	<?=$page->script?>
</script>
