<?php $this->pageType("cms-category")?>
<?php $this->breadcrumbs($category->name, $this->basePath() . "/cms/category/" . $category->url) ?>
<?php $this->headTitle($category->name)?>

<div class="cms-category" id="cms-category-<?=$category->url?>">
	<h1><?=$category->name?></h1>
	
	<ul class="cms-page-list">
		<?php foreach($category->pageList as $page) { ?>
			<?php if($page->isActive) { ?>
				<li>
					<a href="<?=$this->basePath()?>/<?=$page->url?>"><img src="<?=$this->basePath() . $page->filePath('thumbnail')?>" alt="<?=$page->title?>"/></a>
					<h2><a href="<?=$this->basePath()?>/<?=$page->url?>"><?=$page->title?></a></h2>
					<div class="cms-page-preview">
						<?=$page->preview?>
					</div>
				</li>
			<?php } ?>
		<?php } ?>
	</ul>
</div>
